### ISSUE TITLE
please add some alias for ∞ float/double tag

### ISSUE THREAD

**Issue by ch-yx** [tryashtar/nbt-studio#1]
I have to input exactly Infinity**f** to create a Infinity float tag.
please add some alias such as `inf` `Inf` `Infinity` `infinity` `infinityf` `+∞` `∞` `+Infinityf`

**Comment by tryashtar** [comment]
Added in [v1.3](https://github.com/tryashtar/nbt-studio/releases/tag/v1.3):
* `+∞f`, `-∞f`, `∞f` for floats in SNBT
* `+∞d`, `-∞d`, `∞d`, `+∞`, `-∞`, `∞` for doubles in SNBT
* Likewise with `infinity` in place of `∞` (case insensitive)
* Infinity/NaN/true/false work in the tag value window
