### ISSUE TITLE
Bedrock Edition NBT 

### ISSUE THREAD

**Issue by PavelDobCZ23** [tryashtar/nbt-studio#11]
How can I use this to edit chunk data or player data for Minecraft Bedrock Edition?

**Comment by tryashtar** [comment]
Hi, this is not a bedrock world editor, so you can really only edit `level.dat` and exported structure files.

**Comment by PavelDobCZ23** [comment]
> Hi, this is not a bedrock world editor, so you can really only edit `level.dat` and exported structure files.

Are you planning on making some tho? You seem to be one of the very few Minecraft Bedrock tools devs out there, and since all nbt editors editing chunk data or anything associated with it like entities etc... are broken and probably won't get updated, I would appreciate having a working one.

**Comment by tryashtar** [comment]
Honestly, I have thought about adding support for opening bedrock worlds, and displaying all of the NBT files within. However, my experience with [Image Map](github.com/tryashtar/image-map) has revealed to me how much of a pain leveldb is, I really do not want to include 500 DLLs like I'm forced to do in that project.

In addition, anything to do with vanilla minecraft content like blocks or biomes I would definitely say is out of scope of this tool. But there are alternatives for that:
* [UME](https://www.universalminecrafteditor.com/)
* [Amulet](https://github.com/Amulet-Team/Amulet-Map-Editor)
* [MCCToolchest](http://www.mcctoolchest.com/)

**Comment by PavelDobCZ23** [comment]
> > Hi, this is not a bedrock world editor, so you can really only edit `level.dat` and exported structure files.
> 
> Are you planning on making some tho? You seem to be one of the very few Minecraft Bedrock tools devs out there, and since all nbt editors editing chunk data or anything associated with it like entities etc... are broken and probably won't get updated, I would appreciate having a working one.

    I understand, but sadly 2 of those don't work anymore and their development is inactive and Amulet doesn't support entity/tile entity editing, player editing, biome editing and viewing of chunk nbt data itself.

**Comment by PavelDobCZ23** [comment]
> Honestly, I have thought about adding support for opening bedrock worlds, and displaying all of the NBT files within. However, my experience with [Image Map](github.com/tryashtar/image-map) has revealed to me how much of a pain leveldb is, I really do not want to include 500 DLLs like I'm forced to do in that project.
> 
> In addition, anything to do with vanilla minecraft content like blocks or biomes I would definitely say is out of scope of this tool. But there are alternatives for that:
> * [UME](https://www.universalminecrafteditor.com/)
> * [Amulet](https://github.com/Amulet-Team/Amulet-Map-Editor)
> * [MCCToolchest](http://www.mcctoolchest.com/)

Also if u could be able to make it, you could have it as separate tool, but from what I see you don't want to, and it's fine, I understand. As I said 2 of those are broken and one isn't full editor sadly.

**Comment by Giulio-Cusenza** [comment]
> > Honestly, I have thought about adding support for opening bedrock worlds, and displaying all of the NBT files within. However, my experience with [Image Map](github.com/tryashtar/image-map) has revealed to me how much of a pain leveldb is, I really do not want to include 500 DLLs like I'm forced to do in that project.
> > In addition, anything to do with vanilla minecraft content like blocks or biomes I would definitely say is out of scope of this tool. But there are alternatives for that:
> > 
> > * [UME](https://www.universalminecrafteditor.com/)
> > * [Amulet](https://github.com/Amulet-Team/Amulet-Map-Editor)
> > * [MCCToolchest](http://www.mcctoolchest.com/)
> 
> Also if u could be able to make it, you could have it as separate tool, but from what I see you don't want to, and it's fine, I understand. As I said 2 of those are broken and one isn't full editor sadly.

Did you find any solution after that? I am trying to generate some chunks in 1.17 before updating to 1.18, but flying over them is not enough to save them, so I was considering experimenting with the chunk nbt data.

**Comment by tryashtar** [comment]
Sorry, I have no help to offer regarding that objective

**Comment by Giulio-Cusenza** [comment]
> 

Thanks anyway!
