### ISSUE TITLE
File saving, String Tag editing and Ampersand symbols display

### ISSUE THREAD

**Issue by annenveritas** [tryashtar/nbt-studio#19]
### File saving
It seems that currently the way NBT Studio saves files is just writing over the old bytes (can be easily spotted in case of removing parts of NBT structure and saving the file - the filesize stays the same). This doesn't seem to create any problems workflow-wise, but the compression feature kind of loses its point when the compressed bytes just get written on top of the uncompressed ones (in case of enabling the compression after saving previously with some data), resulting in a file that is the same size (probably such thing would barely matter for Minecraft files editing due to their constant resaving by the game, but I like using the Studio for manual own data editing). If I'm not mistaken, it's the `NbtStudio.ExportSettings::Export()`'s `System.IO.File::OpenWrite()` usage that is causing this, maybe just replacing it with the `System.IO.File::Create()` could be an easy fix.

### String Tag editing
When editing String tags, the window is pretty small and isn't resizeable. Not really a bug, but I think it would be a nice thing to have the alternative for when needed. Also, having controls for line wrapping (maybe in the SNBT editor too) would be nice. And maybe a thing that could be helpful when working with large strings, is a multiline tooltip when hovering over a String tag that has line breaks.

### Ampersand symbols display
The tag tree seems to display ampersand symbols as combining underscores (underlining the letter that follows them). Maybe I'm missing something, but I don't think this is indended (although not sure if is any easy to fix).

**Comment by tryashtar** [comment]
Wow if that saving thing is true, that's really embarrassing. I will try to fix that soon.

About string tags, good ideas. Should be easy.

The ampersand thing is this obnoxious behavior for winforms "mnemonics." Like you know how in the toolbar you see File written like that too? Yeah that's because the text is written as &File, the ampersand comes before the letter you can press as a shortcut. I don't know why that isn't just a separate property, since as you've observed it mangles strings with real ampersands in them.

Anyway rant over, it's an easy fix, just double-up the ampersands.

Thanks for these reports!!

**Comment by tryashtar** [comment]
Hey again, I think I've added all of this stuff now, and a few other things. Before I publish a new version, would you mind giving it a try and letting me know if it's up to standard? Thanks!

[NbtStudio.zip](https://github.com/tryashtar/nbt-studio/files/6745428/NbtStudio.zip)

**Comment by annenveritas** [comment]
> Before I publish a new version, would you mind giving it a try and letting me know if it's up to standard?

Yeah, I've just tried it. The resize border seems a bit weird (or maybe it is intended this way?) on the String editor window: it only allows resizing by the bottom right corner while the SNBT editor window freely allows resizing at any point of the window border. And I'm assuming the tooltip feature isn't here yet, judging by that you've pushed the tooltip commit a few hours after uploading this build. Though everything else seems fine, thanks for fixing it :)

**Comment by annenveritas** [comment]
Now I've tried the "Edit N tags" window with strings - there seems to be some problem with recalculating the columns' widths on window resize: a third empty column sometimes appears, sometimes it shrinks, sometimes it becomes wider and takes up seemingly the other columns' space, causing them to shrink, sometimes the named columns are wider than the window, causing a horizontal scrollbar to appear - doesn't seem like this is intended.

**Comment by tryashtar** [comment]
Alright, I think I've taken care of that too now
