### ISSUE TITLE
Suggestion: Another icon set / custom sets

### ISSUE THREAD

**Issue by thebigsmileXD** [tryashtar/nbt-studio#2]
Some years ago i started an attempt at an editor like this too, but the project died off.
If you'd like, you can use the icons https://github.com/thebigsmileXD/WorldObserver/tree/master/WorldObserver/Assets as an additional set to give them a use even after the project died.
I can add the missing region/nbt icons if needed (and probably redesign the B/I/S/D/F/L because they are bigger)

**Comment by tryashtar** [comment]
Good idea, added custom icon sources in v1.12.
No formal documentation for now, but you basically just put [PNGs in a zip folder](https://github.com/tryashtar/nbt-studio/blob/33efdfa69e555b8108d987968dd165c678ab5a10/NbtStudio/IconSource.cs#L336) and import it in the icon select menu.

Here is one for your icon set that I used for testing :)
Any files not included fall back to the default set
[WorldObserverIcons.zip](https://github.com/tryashtar/nbt-studio/files/5544658/WorldObserverIcons.zip)

Here is a complete one:
[UglyPixels.zip](https://github.com/tryashtar/nbt-studio/files/5544781/UglyPixels.zip)
