### ISSUE TITLE
.NET version for version 1.15

### ISSUE THREAD

**Issue by Aarrn33** [tryashtar/nbt-studio#24]
I tried downloading the newest version of nbtstudio and as expected, it asks me to download a new version of .NET. I am under Windows so I download the latest version (5.0.8 x86). I then try to install nbtstudio again but it asks me to download .NET again. I have also tried to install the same version of .NET but x64 it tells me that : "The framework 'Micosoft.WindowsDesktop.App', version '5.0.0' was not found. I also tried with the exact version (5.0.0) but I get the same error.

**Comment by tryashtar** [comment]
Hi there, sorry about this. I'm not sure if I can be much of a help. I looked around and found this, maybe it could be helpful? https://stackoverflow.com/a/68105989

**Comment by Aarrn33** [comment]
Ok, thank you very much, so it worked once I installed the .NET Desktop Runtime 5.0.8 x64.
