### ISSUE TITLE
Free software license

### ISSUE THREAD

**Issue by nfitzen** [tryashtar/nbt-studio#25]
Would you consider releasing this project under a [free software] license, such as [`GPL-3.0-or-later`], Expat/[`MIT`], or [`Apache-2.0`]?
(See also [the GNU Project's license recommendations](https://www.gnu.org/licenses/license-recommendations.html).)

[free software]: https://www.gnu.org/philosophy/free-sw.html

[`GPL-3.0-or-later`]: https://spdx.org/licenses/GPL-3.0-or-later.html "GNU General Public License v3.0 or later"
[`MIT`]: https://spdx.org/licenses/MIT.html "Expat/MIT License"
[`Apache-2.0`]: https://spdx.org/licenses/Apache-2.0.html "Apache License 2.0"

**Comment by tryashtar** [comment]
Great question, thank you for asking about this!
Honestly, I am a bit uncomfortable surrendering the rights to my own work and property. So for now I will say that all rights are reserved.
