### ISSUE TITLE
[Suggestion] Add .nbt Structure Preview GUI

### ISSUE THREAD

**Issue by barraIhsan** [tryashtar/nbt-studio#3]
Add like GUI to preview the structure, just like bedrock edition when you want to save / load structure
![image](https://user-images.githubusercontent.com/57800056/99640222-2e3c9b80-2a7b-11eb-973f-6510fde60010.png)

**Comment by tryashtar** [comment]
Ahahaha... I dunno about this one

**Comment by tryashtar** [comment]
This seems like an appropriate thing to be included in https://github.com/Amulet-Team/Amulet-Map-Editor though :)
