### ISSUE TITLE
Bundle as self-contained app to allow running on Linux

### ISSUE THREAD

**Issue by Jarva-TD** [tryashtar/nbt-studio#30]
When running on Linux the library `libhostpolicy.so` is missing, bundling as a self contained app should fix this issue and allow Linux users to use NBT Studio as well.

**Comment by tryashtar** [comment]
I do have a publish mode for a standalone app, but it bloats the file size to 140 MB.
https://www.mediafire.com/file/rlqbkmspp5h47zw/NbtStudio.exe/file
Does that work for you on linux? I'm not super comfortable uploading these very big files for every release though...

**Comment by Jarva-TD** [comment]
Unfortunately not, that gives the same error about libhostpolicy.so being missing.

**Comment by tryashtar** [comment]
Then I'm not sure what more I can do sadly :(

**Comment by ErrorCraft** [comment]
When .NET 6 comes out (November 2021) you could use .NET MAUI as a cross-platform framework rather than WinForms, which might solve this problem.

**Comment by tryashtar** [comment]
I've definitely been looking forward to maui 😌
From what I've heard, it seems that it will be much more similar to WPF than winforms. I don't have any experience with WPF, but I like to think my separation of model and view in this project is decent enough that it shouldn't be too nightmarish to port all the various forms.
The hard part will probably be porting the control libraries I didn't write, i.e. HexBox and especially TreeViewAdv.
So much work... :(
