### ISSUE TITLE
Error open nbt file

### ISSUE THREAD

**Issue by Max-RM** [tryashtar/nbt-studio#31]
File 
[wa.NBTbx00x00x00xffxffxffxffv.zip](https://github.com/tryashtar/nbt-studio/files/6977200/wa.NBTbx00x00x00xffxffxffxffv.zip)
Error log
[error_log.txt](https://github.com/tryashtar/nbt-studio/files/6977192/error_log.txt)

**Comment by tryashtar** [comment]
That error is correct, the file is just a single random byte
