### ISSUE TITLE
question: Is Linux supported?

### ISSUE THREAD

**Issue by Dhruvin-Purohit** [tryashtar/nbt-studio#32]
I was just wondering if i could use this on Linux since NBT Explorer and Universal Minecraft Editor both don't seem to work (even with WINE). I hope you could add support for Linux soon because i do not want to make my own NBT Editor...

**Comment by tryashtar** [comment]
I was able to get it to work through wine, but it's definitely not "supported" since it's all winforms. Sorry about that, maybe if I were more familiar with linux/cross-platform .NET desktop technologies, I would be able to try

**Comment by Dhruvin-Purohit** [comment]
Thanks for the reply.

Btw I found a VSC extension for NBT editing Definitely not as good as this one But i think I can call this "supported".

**Comment by AutumnalModding** [comment]
> > I was just wondering if i could use this on Linux since NBT Explorer and Universal Minecraft Editor both don't seem to work (even with WINE). I hope you could add support for Linux soon because i do not want to make my own NBT Editor...
> 
> For the record, `NTB Explorer` works just fine in Linux using `mono` instead of `wine`. All you have to do, at least in Ubuntu, is to install `libmono-system-windows-forms4.0-cil` package for the winforms (which pulls `mono-core`)
> 
> I wonder... could `nbt-studio` be compatible with `mono` the same way?

No it doesn't. It's not a CIL image; `mono` refuses to run it.

**Comment by josephdpurcell** [comment]
Confirmed. If anyone finds themselves here, something to consider is https://marketplace.visualstudio.com/items?itemName=Misodee.vscode-nbt which supports editing and works on Linux.
