### ISSUE TITLE
Linux & Mac Os Port?

### ISSUE THREAD

**Issue by Peng1029** [tryashtar/nbt-studio#33]
Are there plans to port this, or Be able to compile for other Operating Systems, I for sure want to use this for bedrock on Linux(Linux & Mac People can play via a launcher with the android version running)
Also this looks pretty good for Java edition

**Comment by tryashtar** [comment]
See #9 / #32

**Comment by zephiii** [comment]
#9 and #32 don't mention macOS.

**Comment by Aces-and-Jacks** [comment]
> #9 and #32 don't mention macOS.

MacOS has a similar architecture to Linux, which isn't supported
