### ISSUE TITLE
Please add optional path to dotnet folder

### ISSUE THREAD

**Issue by sudocpMATHdotPY** [tryashtar/nbt-studio#34]
I can't use the dotnet installer, however i have the dotnet binary folder downloaded. please add a way to set the custom path to the dotnet folder

**Comment by tryashtar** [comment]
How can I do this?

**Comment by sudocpMATHdotPY** [comment]
try adding an input asking for the path to the folder at the start, then use that as the dotnet folder.

**Comment by tryashtar** [comment]
I know how to ask for a file path, I don't know how to "use that as the dotnet folder"

**Comment by tryashtar** [comment]
There is no line of code in this project that imports dot net

**Comment by tryashtar** [comment]
If neither of us know how to solve your issue, then I'm afraid there's nothing to be done
