### ISSUE TITLE
Find/Replace function?

### ISSUE THREAD

**Issue by shimajima** [tryashtar/nbt-studio#46]
Hello @tryashtar and TYSM for carrying on the work of jaquadro! I am trying to do a global find/replace in my world region files. I want to replace every instance of "minecraft:deep_lukewarm_ocean" with "minecraft:ocean" -- is this possible in the current version of NBT Studio?

![image](https://user-images.githubusercontent.com/61395186/185775645-e664138d-4938-43a3-adfb-8197209751ad.png)

**Comment by tryashtar** [comment]
Hello friend. I'm happy to say that this is possible, but sad to say that it might be very slow :(
1. Open your `region` folder, or as many chunk files as you want
![image](https://user-images.githubusercontent.com/26075577/185776669-78d9ab39-f0ab-4149-9add-54d72bb90634.png)
2. Ctrl+F and search for the biome name in "value," click Find All
![image](https://user-images.githubusercontent.com/26075577/185776688-e3e09a94-8f3d-47ff-8373-97a47682680d.png)
This might take way longer than it reasonably should
3. Once it's done, click Edit
![image](https://user-images.githubusercontent.com/26075577/185776724-fcbff45a-5231-4d5b-ac57-24227f3e2ff8.png)
4. Type the value again in the "find" and the new value in the "replace" box
![image](https://user-images.githubusercontent.com/26075577/185776744-5f7250cb-045f-402e-8cba-cd39aace5a57.png)
5. Press OK and save

Let me know if this works for you

**Comment by shimajima** [comment]
It worked fantastic! It took around 5 minutes to replace 23,432 instances of the string, which seems pretty fast to me!  :)

**Comment by shimajima** [comment]
@tryashtar, I kind of spoke too soon. It was ok using this method to find/replace a string in 1 (one) region file. But we have to do it in 600 region files, which NBT Studio just can’t handle.  We get crashes even on monster hardware. Is there any way to make the find/replace much more efficient and faster? I send you an email with a idea which maybe could incorporate LINQ.
