### ISSUE TITLE
Text doesn't fully render in the tree

### ISSUE THREAD

**Issue by ErrorCraft** [tryashtar/nbt-studio#5]
The text doesn't seem to fully render in the tree. This might happen because I'm using a 1920x1080 screen, since I was having [issues with blurry text](https://user-images.githubusercontent.com/51973682/102924900-b8b95600-4492-11eb-85ec-c018ff115888.png) earlier. (The blurry text is somehow fixed by pressing "Open Folder," but that causes this to happen.)

Images:
![image](https://user-images.githubusercontent.com/51973682/102923905-dbe30600-4490-11eb-82b7-224780dcc0ab.png)
![image](https://user-images.githubusercontent.com/51973682/102924039-1351b280-4491-11eb-90d6-13c132bff221.png)

**Comment by tryashtar** [comment]
Hm, that's a bit annoying. I'm curious, when you select an item, does the blue background get cut off at the exact same pixel as the text?
I've had minor issues like this myself, but never to this extent. Probably something to do with `graphics.MeasureString`.

**Comment by ErrorCraft** [comment]
Yep, the blue background gets cut off there as well.
![image](https://user-images.githubusercontent.com/51973682/102939720-122f7e00-44af-11eb-9c9b-26f9431e4d8d.png)
