### ISSUE TITLE
图标预览界面缺少关闭按钮

### ISSUE THREAD

**Issue by hyplant** [tryashtar/nbt-studio#51]
在更改图标的界面中，可以预览所有图标，但弹出的预览窗口没有关闭按钮。

**Comment by hyplant** [comment]
On the Change icon screen, you can preview all ICONS, but the preview window that pops up does not have a close button.

**Comment by tryashtar** [comment]
You close it by pressing the eye again. I have no idea why I decided to do it that way 😅
