### ISSUE TITLE
(De)Select All Children raised an exception

### ISSUE THREAD

**Issue by chatcoda** [tryashtar/nbt-studio#7]
First of all thanks for this very handy tool.
Exception System.InvalidOperationException: Collection was modified.
I had a quick look at your code.
Changing `foreach (var node in selected)` to `foreach (var node in selected.ToList())` @ lines 1147 and 1156 in \NbtStudio\UI\MainForm.cs fixes it.

**Comment by tryashtar** [comment]
Ah thanks for the catch
