### ISSUE TITLE
NBT Studio causing realm's submission checking program to delete scoreboard.dat

### ISSUE THREAD

**Issue by SnaveSutit** [tryashtar/nbt-studio#8]
Seems like NBT Studio uses compression speed parameter 1 when saving files? while minecraft uses 6. While this isn't usually a problem it causes the realms map checking program to freak out and delete the scoreboard.dat because it's not what it expected. At least that's what I understand from this:
![image](https://user-images.githubusercontent.com/28514936/104343279-be222300-54c9-11eb-8868-a9472b63ef6d.png)

**Comment by tryashtar** [comment]
Oh wow, thanks for letting me know. Currently fNbt handles the saving so I'll have to tweak it in there. I'll try to get you a test version soon

**Comment by boq** [comment]
It seems that those two fields (compression method and os) are just informative and not used (at least not in zlib), so this is not a cause of incompatibility. Sorry for misdirection.

However, when decompressing files (maybe only above certain size?) `gzip` tool gives this hint:
```
gzip: scoreboard.gz: decompression OK, trailing garbage ignored
```

After looking at code that validates maps for Realms, it seems that used compression library tries to decompress as much as possible, re-initiating decompression if there is something left in buffer and causing this error.

It seems that Java's `GZIPInputStream` also tries it, [but discards invalid data](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/util/zip/GZIPInputStream.java#L227-L242).

This trailed data itself looks like random non-zero bytes, so no idea where is comes from (doesn't seems like NBT).

Also, potentially related observation: when this specific NBT file is decompressed, it also has trailing data (this time it's mostly zeroes)

**Comment by tryashtar** [comment]
Thanks for the info, that's interesting. I'm currently at the mercy of .NET's gzip implementation, but I'll try to get it worked out.

**Comment by tryashtar** [comment]
@SnaveSutit Would you mind uploading the normal/broken scoreboard files so I could try with those? With the random `scoreboard.dat` files on my computer, I get byte-for-byte identical output when saving files produced by Minecraft except for one byte in the header (presumably this compression mode flag):
```diff
--- D:\~No Sync\Downloads\original.dat
+++ D:\~No Sync\Downloads\scoreboard.dat
@@ -1,4 +1,4 @@
-1f8b 0800 0000 0000 0000 d57d 4b8c a459
+1f8b 0800 0000 0000 0400 d57d 4b8c a459
 7656 5455 66bd facd 4c8f 6d1e 43d1 9933
 e301 dfe6 bfef 7bcd 6cdc d336 8c99 1997
 a69b 8111 12c9 7d66 c654 6444 3a22 b2bb
```

**Comment by tryashtar** [comment]
Is this still causing trouble?

**Comment by SnaveSutit** [comment]
Not that I know of.
